# Generated by Django 4.1 on 2025-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviesession",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                null=True, upload_to="cinema.models.upload_movie_image"
            ),
        ),
    ]
