# Generated by Django 4.1 on 2025-05-19 12:34

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_moviesession_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviesession",
            options={"ordering": ["-show_time"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                null=True, upload_to=cinema.models.upload_movie_image
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("movie_session", "row", "seat")},
        ),
    ]
